name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Asegúrate de usar una versión compatible con tus dependencias

    - name: Install dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "baxaal"  # reemplaza con tu nombre de aplicación en Heroku
        heroku_email: "isa125.rosas@gmail.com"  # reemplaza con tu email asociado a Heroku
